embed_dim: 256
action_dim: 2
in_c: 2
out_c: 1
epochs: 20
batch_size: 1024
learning_rate: 0.00014
model_type: 'JEPA2Dv2'
data_path: '/scratch/DL24FA/train'
optimizer_type: 'adam'
scheduler_type: 'onecycle'

# action regularization
action_reg_hidden_dim: 32
lambda_reg: 0

vicreg_loss:
  lambda_invariance: 1
  mu_variance: 25
  nu_covariance: 1
