embed_dim: 128
action_dim: 2
in_c: 2
epochs: 20
batch_size: 1024
learning_rate: 0.0001
model_type: 'AdversarialJEPAWithRegularization'
data_path: '/scratch/DL24FA/train'

# action regularization
action_reg_hidden_dim: 32
lambda_reg: 1

# adversarial regularization
delta_gen: 5

vicreg_loss:
  lambda_invariance: 1
  mu_variance: 25
  nu_covariance: 1
